// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iujkcxshaolbdlenucot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1amtjeHNoYW9sYmRsZW51Y290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNDI0MTUsImV4cCI6MjA2NjkxODQxNX0.rDOZuAf5TFAlSwAK5Gz20cy7nkX_-FAadu99ph2LFBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});