// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eobxruljpcpbymkmwygk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvYnhydWxqcGNwYnlta213eWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzAyNjgsImV4cCI6MjA2NjMwNjI2OH0.0PEFQ09LF8Wbx5jxoPBc2qbucUkulmzqBUud_PMdEFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});